# Generated by Django 3.2.8 on 2021-10-10 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rss_link', models.CharField(max_length=200)),
                ('click_tracking', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=4000)),
                ('author', models.CharField(max_length=100, null=True)),
                ('link', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.site')),
            ],
            options={
                'unique_together': {('title', 'site')},
            },
        ),
    ]
